version: 2.1
orbs:
  terraform-orb: bankrate/terraform@1.0.0
jobs:
  validate-terraform:
    steps:      
      - terraform-orb/validate:
          infrastructure_dir: ./aws-infrastructure          

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: master
