version: 2.1
jobs:
  terraform-validate:
    docker:
      - image: hashicorp/terraform:light
    working_directory: ~/repo/aws-infrastructure
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: terraform init
          command: terraform init
      - run:
          name: terraform validate
          command: terraform validate
  terraform-apply:
    docker:
      - image: hashicorp/terraform:light
    working_directory: ~/repo/aws-infrastructure
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: terraform apply
          command: terraform apply -auto-approve
  serverless-build:
    docker:
      - image: circleci/node:10.15.1
    working_directory: '~/repo'
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Installations
          command: npm ci
      - run:
          name: Run ESLint
          command: npm run lint
  serverless-deploy:
    docker:
      - image: circleci/node:10.15.1
    working_directory: '~/repo'
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Installations
          command: npm ci
      - run:
          name: Serverless deploy
          command: npm run deploy
      - run:
          name: Inject REACT_APP_API_URL env variable
          command: |
            curl -X POST --user ${UPDATE_FRONTEND_ENV_VARS_TOKEN}: \
              -H 'Content-Type: application/json' \
              --data @env/update_rest_api_url.json \
              https://circleci.com/api/v1.1/project/github/ScottLogic/search-data-exports-frontend/envvar
      - run:
          name: Inject REACT_APP_WEBSOCKET_ENDPOINT env variable
          command: |
            curl -X POST --user ${UPDATE_FRONTEND_ENV_VARS_TOKEN}: \
              -H 'Content-Type: application/json' \
              --data @env/update_websocket_url.json \
              https://circleci.com/api/v1.1/project/github/ScottLogic/search-data-exports-frontend/envvar
  inject-frontend-env-variables:
    docker:
      - image: byrnedo/alpine-curl
    working_directory: '~/repo'
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Inject REACT_APP_API_URL env variable
          command: |
            curl -X POST --user ${UPDATE_FRONTEND_ENV_VARS_TOKEN}: \
              -H 'Content-Type: application/json' \
              --data @env/update_rest_api_url.json \
              https://circleci.com/api/v1.1/project/github/ScottLogic/search-data-exports-frontend/envvar
      - run:
          name: Inject REACT_APP_WEBSOCKET_ENDPOINT env variable
          command: |
            curl -X POST --user ${UPDATE_FRONTEND_ENV_VARS_TOKEN}: \
              -H 'Content-Type: application/json' \
              --data @env/update_websocket_url.json \
              https://circleci.com/api/v1.1/project/github/ScottLogic/search-data-exports-frontend/envvar

workflows:
  version: 2
  build-deploy:
    jobs:
      - terraform-validate
      - terraform-apply
          requires:            
            - terraform-validate
          filters:
            branches:
              only: sde-128-backend-repo-cleanup
      - serverless-build
      - serverless-deploy:
          requires:
            - serverless-build
            - terraform-apply
          filters:
            branches:
              only: sde-128-backend-repo-cleanup
