version: 2.1
orbs:
  terraform: ovotech/terraform@1.5.1
jobs:
  terraform-validate:
    docker:
      - image: hashicorp/terraform:light        
    steps:
      - terraform/validate:
          path: ./aws-infrastructure
  
workflows:
  version: 2
  build-deploy:
    jobs:
      - terraform-validate
