version: 2.1
orbs:
  tf: ngs/terraform@0.0.1
jobs:
  terraform-validate:
    docker:
      - image: hashicorp/terraform
    working_directory: ./aws-infrastructure
    steps:
      - checkout
      - tf/init
      - tf/tf:
          command: validate
 
workflows:
  version: 2
  build-deploy:
    jobs:
      - terraform-validate          
