version: 2.1
orbs:
  terraform: bankrate/terraform@1.1.2
workflows:
  version: 2
  build-deploy:
    jobs:
      - terraform/validate:
          infrastructure_dir: aws-infrastructure
          name: terraform-validate
