service: sde-v2-2

plugins:
  - serverless-webpack
  - serverless-step-functions

custom:
  esEndpoint: ${ssm:/sde-${self:provider.stage}-elasticsearch-endpoint}
  s3BucketName: ${ssm:/sde-${self:provider.stage}-s3-bucket-name}
  webpack:
    includeModules: true # enable auto-packing of external modules

package:
  individually: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
  tags:
    project: "${self:service}"

  iamRoleStatements:
    - Effect: Allow
      Action:
        - states:DescribeExecution
        - states:SendTaskSuccess
        - execute-api:Invoke
        - es:ESHttpPost
        - s3:PutObject
        - s3:PutObjectAcl
      Resource:
        - "*"

functions:
  pushNotificationOpenConnection:
    handler: functions/pushNotificationOpenConnection.handler
    description: Notified when client connects to websocket to complete activity
    events:
      - websocket:
          route: OpenConnection
  pushNotificationToClient:
    handler: functions/pushNotificationToClient.handler
    description: Send report URL to client over websocket
    environment:
      WEBSOCKET_ENDPOINT_URL: !Join
        - ""
        - - "https://"
          - !Ref WebsocketsApi
          - ".execute-api."
          - ${opt:region, self:provider.region}
          - ".amazonaws.com/"
          - ${opt:stage, self:provider.stage}
  downloadRequest:
    handler: functions/downloadRequest.handler
    events:
      - http:
          path: download-request
          method: post
          cors: true
    environment:
      CSV_DOWNLOAD_REQUEST_STEP_FUNCTION_ARN: test-1
      OPEN_CONNECTION_ACTIVITY_ARN: test-2
  search:
    handler: functions/search.handler
    events:
      - http:
          path: search
          method: post
          cors: true
    environment:
      ES_SEARCH_API: ${self:custom.esEndpoint}
  graphicalReport:
    handler: functions/graphicalReport.handler
    events:
      - http:
          path: report/graphical
          method: post
          cors: true
    environment:
      ES_SEARCH_API: ${self:custom.esEndpoint}
      S3_BUCKET_NAME: ${self:custom.s3BucketName}
  hybridReport:
    handler: functions/hybridReport.handler
    runtime: nodejs8.10
    events:
      - http:
          path: report/hybrid
          method: post
          cors: true
    environment:
      ES_SEARCH_API: ${self:custom.esEndpoint}
      S3_BUCKET_NAME: ${self:custom.s3BucketName}
  sendEmail:
    handler: functions/sendEmail.handler
    environment:
      EMAIL_SENDER_ADDRESS  : "rharrington@scottlogic.com"