Resources:
  scheduledDailyDigestsLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:service}-${self:custom.stage}-scheduledDailyDigestsLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: inlinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                Resource:
                  - !Join
                      - ''
                      -
                        - 'arn:aws:dynamodb:'
                        - Ref: 'AWS::Region'
                        - ':'
                        - Ref: 'AWS::AccountId'
                        - ':table/'
                        - Ref: SubscriptionsTable
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Join
                      - ':'
                      -
                        - 'arn:aws:lambda'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'function'
                        - '${self:service}-${self:custom.stage}-calculateUserDailyDigest'
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                Resource:
                  - !Join
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - log-group
                        - '/aws/lambda/${self:service}-${self:custom.stage}*:*'
              - Effect: Allow
                Action:
                  - logs:PutLogEvents
                Resource:
                  - !Join
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - log-group
                        - '/aws/lambda/${self:service}-${self:custom.stage}*:*:*'
